### PR TITLE
Pegs tui

### PR DESCRIPTION
**Pull request by smk762**

### CODE REVIEW

**Comment by smk762** [comment]
new logo, gateways info option, oraclesfund fix, frame for Pegs TUI (methods adding in progress)

**Comment by smk762** [comment]
added pegs tui menu options
combined prepare gateway deposit, execute gateway deposit and claim gateway deposit into single tui option
tweaked some inputs to offer a list of selectable values instead of raw text input.

**Comment by smk762** [comment]
Can use these launch params for testing:
`komodod -ac_name=PEGSTEST -ac_supply=5000 -ac_reward=800000000 -ac_sapling=1 -addnode=116.203.120.163 -ac_snapshot=1440 -addnode=116.203.120.91 -ac_cc=2 -ac_import=PEGSCC -ac_end=1 -ac_perc=0 -ac_cbopret=7 -debug=gatewayscc-2 -earlytxid=5ccdff0d29f2f47fb1e349c1ff9ae17977a58763abacf693cd27e98b38fad3f3 -pubkey=$pubkey`

**Comment by tonymorony** [comment]
Great job! Thank you, will test it

**Pull request merged**
